-- create_tables.sql
-- Projeto: Sistema de Controle de Vendas (Oracle)
-- Autor: Bruno Henrique Popko
-- Data: (adicione a data)

SET DEFINE OFF;
-- (Opcional) criar tabelas no schema atual.

-- Tabela: clientes
CREATE TABLE clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(150),
    telefone VARCHAR2(20),
    cidade VARCHAR2(50),
    estado CHAR(2),
    data_cadastro DATE DEFAULT SYSDATE
);

-- Tabela: produtos
CREATE TABLE produtos (
    id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150) NOT NULL,
    categoria VARCHAR2(50),
    preco NUMBER(12,2) DEFAULT 0,
    estoque NUMBER DEFAULT 0,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S','N'))
);

-- Tabela: vendedores
CREATE TABLE vendedores (
    id_vendedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(120) NOT NULL,
    email VARCHAR2(150),
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S','N'))
);

-- Tabela: vendas
CREATE TABLE vendas (
    id_venda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER NOT NULL,
    id_vendedor NUMBER NOT NULL,
    data_venda DATE DEFAULT SYSDATE NOT NULL,
    valor_total NUMBER(14,2) DEFAULT 0 NOT NULL,
    status VARCHAR2(20) DEFAULT 'FECHADA' NOT NULL,
    observacao VARCHAR2(4000),
    CONSTRAINT fk_vendas_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
    CONSTRAINT fk_vendas_vendedor FOREIGN KEY (id_vendedor) REFERENCES vendedores(id_vendedor)
);

-- Tabela: itens_venda
CREATE TABLE itens_venda (
    id_item NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda NUMBER NOT NULL,
    id_produto NUMBER NOT NULL,
    quantidade NUMBER(10,2) DEFAULT 1 NOT NULL,
    valor_unitario NUMBER(12,2) DEFAULT 0 NOT NULL,
    subtotal NUMBER(14,2) GENERATED ALWAYS AS (quantidade * valor_unitario) VIRTUAL,
    CONSTRAINT fk_itens_venda_venda FOREIGN KEY (id_venda) REFERENCES vendas(id_venda) ON DELETE CASCADE,
    CONSTRAINT fk_itens_venda_produto FOREIGN KEY (id_produto) REFERENCES produtos(id_produto)
);

-- Índices (para performance em joins e filtros comuns)
CREATE INDEX idx_vendas_data ON vendas (data_venda);
CREATE INDEX idx_vendas_cliente ON vendas (id_cliente);
CREATE INDEX idx_itens_venda_produto ON itens_venda (id_produto);

-- Comentários (documentação das tabelas/colunas)
COMMENT ON TABLE clientes IS 'Clientes/lojas que realizam compras';
COMMENT ON COLUMN clientes.nome IS 'Nome do cliente ou razão social';
COMMENT ON COLUMN clientes.email IS 'Email de contato do cliente';
COMMENT ON COLUMN clientes.telefone IS 'Telefone de contato';
COMMENT ON COLUMN clientes.data_cadastro IS 'Data de cadastro no sistema';

COMMENT ON TABLE produtos IS 'Catálogo de produtos';
COMMENT ON COLUMN produtos.preco IS 'Preço unitário atual do produto';
COMMENT ON COLUMN produtos.estoque IS 'Quantidade em estoque';

COMMENT ON TABLE vendedores IS 'Equipe comercial / vendedores';

COMMENT ON TABLE vendas IS 'Cabeçalho da venda (nota)';
COMMENT ON COLUMN vendas.valor_total IS 'Valor total calculado da venda (deve ser conferido)';
COMMENT ON COLUMN vendas.status IS 'Status da venda: ABERTA, FECHADA, CANCELADA';

COMMENT ON TABLE itens_venda IS 'Itens relacionados a cada venda';
COMMENT ON COLUMN itens_venda.valor_unitario IS 'Preço aplicado naquele item (snapshot)';
COMMENT ON COLUMN itens_venda.subtotal IS 'Quantidade * valor_unitario (calculado)';

-- BOAS PRÁTICAS: checar restrições de integridade e privilégios (ex.: grants)
-- Exemplo (opcional) dar permissões a outro usuário/schema:
-- GRANT SELECT, INSERT, UPDATE, DELETE ON clientes TO outro_usuario;

COMMIT;